---

- name: SHOW VERSION
  hosts: "172.16.12.3"
  gather_facts: false
  connection: network_cli

  tasks:
    - name: run the command 'show version'
      ios_command:
        commands: show version
