---

- name: SHOW VERSION
  hosts: CPE-1
  gather_facts: true
  connection: network_cli
  vars:
   creds:
     host: "{{ansible_host}}"
     username: "{{ansible_user}}"

  tasks:
    - ios_facts:
        provider: "{{creds}}"
    - debug:
        var: ansible_net_model
