---
- name: Wormhole Team!
  hosts: all
  vars_files:
    - "{{ var_file }}"
  tasks:

  - name: Hello!
    shell: echo "Hi! Welcome to wormhole team.{{pname}}, {{city}}, {{state}}"
           
    register: results
  - set_fact:
      myvalue: "{{ results.stdout | regex_search(regexp,'^TASK') }}"

  - copy: content={{ find_output }} dest=/home/stack/wormhole/error.log
